### ISSUE TITLE
Px-app-nav always show description even on smallscreen

### ISSUE THREAD

**Issue by fjacquel** [PredixDev/px-app-nav#24]
Hi,
## Expected behavior and actual behavior:

The px-app-nav is supposed to hide description and only show icons on smaller screen. My problem is that the px-app-nav is always showing both icon/description after page loading.
## Steps to reproduce the problem:
1. Resize the browser until the px-app-nav is automatically hiding the description.
2. Refresh the page. The px-app-nav is shown big and overlap on the view.
3. I would expect the px-app-nav to hide description.
## Environment

win 7, Chrome

Thanks in advance,
Flo

**Comment by randyaskin** [comment]
This is caused by the commented line here: 
https://github.com/PredixDev/px-app-nav/blob/master/px-app-nav.html#L257

Eric and Yash did that to allow developers to pass "nav-expanded" in as a property to change the default behavior (see Issue #7). Our team needs to figure out how to support both - make it responsive by default, but allow the developer to override.

**Comment by fjacquel** [comment]
Thanks for the info Randy.

**Comment by gedesigntech** [comment]
A fix was made, the component should now be collapsed initially when the attribute 'nav-expanded' is set to 'false'.  Please see v1.10.1

**Comment by fjacquel** [comment]
Hi Henry, the extra attribute is working but I think the solution can be improved.
When resizing the browser window, the navbar is automatically expanding/collapsing depending on the available space. It would be nice to execute the same code when the component is rendered first to determine whether the navbar shall be expanded or collapsed.
