### ISSUE TITLE
Adding custom html tags to px-app-nav navItems and sub items.

### ISSUE THREAD

**Issue by anurag-tyagi** [PredixDev/px-app-nav#34]
# Submit an Issue

## Expected behavior and actual behavior:
Currently if we add a HTML tag to the navItem label text , it is displayed as it is and not rendered as HTML tag. The user should be able to add html tags like span div etc to the navItem label 

## Steps to reproduce the problem:
Add a html code to the label 
 var txt1 = '<span style="float: right;">Hello</span>';              // Create text with HTML
 var tab = [{'label':'CN' + txt1,
			'state':"CN",
		}]

## Screenshots (_optional, but very helpful_):

Attached screenshot is what I am trying to achieve
![2415-untitled](https://cloud.githubusercontent.com/assets/18675522/22726820/81cd1218-edfb-11e6-8695-125b2b4bbfe1.png)

If there is already a way to achieve the same let me know, else please see if it can be added.

**Comment by runn-vermel** [comment]
Let me repeat back to you, to make sure i understand what the issue is:

You'd like to create HTML tags (with content), and insert them using the data binding feature?

If i understand what you want, this is not possible with Polymer. the reasons for that is that leaving you open to create HTML tags can leave you open to XSS attacks.

So, this is a limitation of Polymer, put in place for your protection.

Please let me know if I misunderstood what it is you'd like to do.

**Comment by anurag-tyagi** [comment]
Yes thats what I wanted to create.

**Comment by runn-vermel** [comment]
Sadly, as i said, we can't help you there - that's a limitation of Polymer, put there for your own protection to avoid XSS attacks. :(
