### ISSUE TITLE
px-app-nav "auth" class and content not displaying correctly

### ISSUE THREAD

**Issue by austinmcdaniel** [PredixDev/px-app-nav#40]
## Expected behavior and actual behavior:
```
<px-app-nav nav-items="[[navItems]]">
<div class="auth">AUTH CONTENT</div>
</px-app-nav>
```

I expected the above to include the AUTH CONTENT at the base of the navigation bar. Instead the item is placed below the nav bar and isn't treated as if it is part of the nav bar.

## Steps to reproduce the problem:
See above.

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
px-app-nav version 1.10.10
Chrome 57.0.2987.133
Windows 7
Dell laptop.

## Screenshots (_optional, but very helpful_):
![image](https://cloud.githubusercontent.com/assets/16106173/25440530/59578db2-2a65-11e7-8980-5f03b0b29487.png)

**Comment by randyaskin** [comment]
I could change px-app-nav to have a flex-justify to push the nav to the top and the auth to the bottom, but I'm afraid of what unintended consequences that may have on other people's implementations.

Because the auth div is in the component's lightDom, you actually have complete control over the styling of it, you can set it's position and offset from the bottom of the nav, like so: https://codepen.io/randyaskin/pen/MmpgEm?editors=1100
