### ISSUE TITLE
Vertical state overlays px-branding-bar

### ISSUE THREAD

**Issue by akshayeshenoi** [PredixDev/px-app-nav#76]
## Expected behavior and actual behavior:
Branding bar shouldn't be overlaid.

## Steps to reproduce the problem:
```html
    <!-- Branding -->
    <px-branding-bar></px-branding-bar>
    <!-- Nav bar -->
    <px-app-nav
      slot="app-nav"
      selected-route="{{selected}}"
      items='[[navItems]]'
      vertical>
    </px-app-nav>
```

## Screenshots (_optional, but very helpful_):
![image](https://user-images.githubusercontent.com/7693429/29974338-18eda720-8f50-11e7-9099-ec6c2bbd43f5.png)

## Fix
Add `top: 2rem` css to px-app-nav.

**Comment by randyaskin** [comment]
We can't guarantee that all applications will use the px-branding-bar, or they may want to bump the branding bar to the right instead of bumping the app-nav down (which is a valid design alternative) - you should handle this in your application instead. Also note that the branding bar does not appear on small devices by design. You should handle this in your application, e.g. https://github.com/PredixDev/px-sample-app/blob/master/sass/px-sample-app.scss#L107-L112
